apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/climacs-net/hello-world-my-app.git
    targetRevision: HEAD
    path: apps/cat-website
  destination:
    server: https://kubernetes.default.svc
    namespace: cat-website-n
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/climacs-net/hello-world-my-app.git
    targetRevision: HEAD
    path: apps/nginx-myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-myapp
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/climacs-net/hello-world-my-app.git
    targetRevision: HEAD
    path: apps/tomcat-myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: tomcat-myapp
  syncPolicy:
    automated: {}

