apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-myapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/climacs-net/app-of-apps.git
    targetRevision: tabish-app-of-apps
    path: manifest/nonprod/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
